# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
orbs:
  node: circleci/node@4.1.0
jobs:
  build-back:
    docker: 
      - image: circleci/node:15.4.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    parameters:
      app-dir:
        default: ~/project/backend
        description: Path to the directory containing your package.json file. Not needed if package.json lives in the root.
        type: string
      pkg-manager:
        default: yarn
        description: Select the default node package manager to use.
    steps:
      - checkout
      - run: cd ~/project/backend
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - package.json
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}     
      # run tests!
      - run: yarn run test 
 

workflows:
  version: 2
  -build:
    jobs:
      - build-back:
          filters:
            branches:
              only: 
                - develop
                - main