branches:
    only:
        - main
notifications:
    email: false

dist: bionic
os: linux
language: node_js

test: &test
    dist: bionic
    os: linux
    language: node_js
    stage: Test
    node_js:
        - node
    cache:
        - yarn
        - directories:
              - node_modules
    matrix:
        fast_finish: true
    before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s --
        - export PATH="$HOME/.yarn/bin:$PATH"
    install:
        - yarn install
    script:
        - yarn run lint
        - yarn workspace backend run test

jobs:
    include:
        - <<: *test
          if: type = pull_request
          env:
              - WORKING_DIR="$TRAVIS_BUILD_DIR/backend"
