# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
gem 'capistrano'
# gem "rails"
gem 'capistrano-docker', github: 'netguru/capistrano-docker'
gem 'capistrano-yarn'

